[fcitx5-pinyin-moegirl]
src.github = "outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.3.0."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.3.0/zhwiki-$ver.dict"

[ndrop]
src.git = "https://github.com/Schweber/ndrop"
fetch.git = "https://github.com/Schweber/ndrop"

[orca-ide]
src.github = "stablyai/orca"
src.prefix = "v"
fetch.url = "https://github.com/stablyai/orca/releases/download/v$ver/orca-ide_$ver_amd64.deb"

[teamspeak-management-tools]
src.github = "KunoiSayami/teamspeak-management-tools.rs"
fetch.github = "KunoiSayami/teamspeak-management-tools.rs"

[tela-icon-theme-nighty]
src.git = "https://github.com/vinceliuice/tela-icon-theme"
fetch.git = "https://github.com/vinceliuice/tela-icon-theme"
