[applet-window-appmenu]
src.github = "psifidotos/applet-window-appmenu"
fetch.github = "psifidotos/applet-window-appmenu"

[baidupcs-go]
src.github = "qjfoidnh/BaiduPCS-Go"
fetch.github = "qjfoidnh/BaiduPCS-Go"

[clash-rules-dat-country]
src.cmd = "date +%Y%m%d"
fetch.url = "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"

[clash-rules-dat-geoip]
src.cmd = "date +%Y%m%d"
fetch.url = "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat"

[clash-rules-dat-geosite]
src.cmd = "date +%Y%m%d"
fetch.url = "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"

[clash-webui-dashboard]
src.git = "https://github.com/Dreamacro/clash-dashboard"
src.branch = "gh-pages"
fetch.url = "https://github.com/Dreamacro/clash-dashboard/archive/refs/heads/gh-pages.zip"

[clash-webui-yacd]
src.git = "https://github.com/haishanh/yacd"
src.branch = "gh-pages"
fetch.url = "https://github.com/haishanh/yacd/archive/refs/heads/gh-pages.zip"

[clash-webui-yacd-meta]
src.git = "https://github.com/MetaCubeX/Yacd-meta"
src.branch = "gh-pages"
fetch.url = "https://github.com/MetaCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip"

[fcitx5-pinyin-moegirl]
src.github = "outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict"

[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[miraclecast-my]
src.git = "https://github.com/albfan/miraclecast"
fetch.github = "albfan/miraclecast"

[wemeet]
src.manual = "3.14.0.401"
fetch.url = "https://updatecdn.meeting.qq.com/cos/1b001ef75914a1d6948decb8c2550b47/TencentMeeting_0300000000_3.14.0.401_x86_64_default.publish.deb"

[yet-another-spotify-tray]
src.git = "https://github.com/macdems/yet-another-spotify-tray"
fetch.url = "https://github.com/macdems/yet-another-spotify-tray/archive/refs/heads/main.zip"
