# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  siyuan-patch = {
    pname = "siyuan-patch";
    version = "v3.8.3";
    src = fetchFromGitHub {
      owner = "demoshang";
      repo = "siyuan-patch";
      rev = "v3.8.3";
      fetchSubmodules = false;
      sha256 = "sha256-gWKyQPGjtx/OTGVeHFAbiTzm1tAM8Bfm3wa2pLgV7tk=";
    };
  };
}
