# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  applet-window-appmenu = {
    pname = "applet-window-appmenu";
    version = "v0.8.0";
    src = fetchFromGitHub {
      owner = "psifidotos";
      repo = "applet-window-appmenu";
      rev = "v0.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-ckbrSmZowy1+rp17C8OBnpX8wHRSmDRcdYjOhj4JunQ=";
    };
  };
  applet-window-buttons6 = {
    pname = "applet-window-buttons6";
    version = "326382805641d340c9902689b549e4488682f553";
    src = fetchgit {
      url = "https://github.com/moodyhunter/applet-window-buttons6";
      rev = "326382805641d340c9902689b549e4488682f553";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-POr56g3zqs10tmCbKN+QcF6P6OL84tQNkA+Jtk1LUfY=";
    };
    date = "2024-04-05";
  };
  baidupcs-go = {
    pname = "baidupcs-go";
    version = "v3.9.5";
    src = fetchFromGitHub {
      owner = "qjfoidnh";
      repo = "BaiduPCS-Go";
      rev = "v3.9.5";
      fetchSubmodules = false;
      sha256 = "sha256-zNodRQzflOOB3hAeq4KbjRFlHQwknVy+4ucipUcoufY=";
    };
  };
  clash-webui-yacd = {
    pname = "clash-webui-yacd";
    version = "09eb9389a7109eafd35118cbf7c2ac0860190b01";
    src = fetchurl {
      url = "https://github.com/haishanh/yacd/archive/09eb9389a7109eafd35118cbf7c2ac0860190b01.zip";
      sha256 = "sha256-983O0cNc+30y4/GO/yTRlWLTAFt+pB5Z90jA3b7en0Q=";
    };
    date = "2023-10-30";
  };
  clash-webui-yacd-meta = {
    pname = "clash-webui-yacd-meta";
    version = "b66b1d0393bd284b7a40329f95eae3746bb102be";
    src = fetchurl {
      url = "https://github.com/MetaCubeX/Yacd-meta/archive/b66b1d0393bd284b7a40329f95eae3746bb102be.zip";
      sha256 = "sha256-S6gLic5TeCkYDQsKmasr4/H5+ca8hP5qTzpVDXZHzdY=";
    };
    date = "2023-12-29";
  };
  double-entry-generator = {
    pname = "double-entry-generator";
    version = "v2.5.0-homebrew";
    src = fetchFromGitHub {
      owner = "deb-sig";
      repo = "double-entry-generator";
      rev = "v2.5.0-homebrew";
      fetchSubmodules = false;
      sha256 = "sha256-TiXTRgbwElTptx5QhmgIfd8pirWTv5EHgO5RxYWeTtU=";
    };
  };
  fcitx5-pinyin-moegirl = {
    pname = "fcitx5-pinyin-moegirl";
    version = "20240309";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20240309/moegirl.dict";
      sha256 = "sha256-ir9WQA2cz8VLL46/GaLTFAnL/H5vKWq3sbywHTcAKb8=";
    };
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20240210";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20240210.dict";
      sha256 = "sha256-vNHS5n3TqSwpUx2wG26w7rK6jSqrvLANeG2n0vA4iYk=";
    };
  };
  geonames-admin1Codes = {
    pname = "geonames-admin1Codes";
    version = "2024-04-13T17:13:59+00:00";
    src = fetchurl {
      url = "https://download.geonames.org/export/dump/admin1CodesASCII.txt";
      sha256 = "sha256-bqzosmnNTJY12PhjGFfAviyz+2NiSV938X8mbvcyjxE=";
    };
  };
  geonames-admin2Codes = {
    pname = "geonames-admin2Codes";
    version = "2024-04-13T17:14:01+00:00";
    src = fetchurl {
      url = "https://download.geonames.org/export/dump/admin2Codes.txt";
      sha256 = "sha256-Aqup2XMhQHCI/0nTkomktXGXZaH9gPAEFCmbN05qKrA=";
    };
  };
  geonames-cities500 = {
    pname = "geonames-cities500";
    version = "2024-04-13T17:13:56+00:00";
    src = fetchurl {
      url = "https://download.geonames.org/export/dump/cities500.zip";
      sha256 = "sha256-ALxBsKpARX7bVM9CA+hTsq3Gtwy6YeC4gKT+eotYNhA=";
    };
  };
  kes = {
    pname = "kes";
    version = "2024-03-28T12-56-37Z";
    src = fetchFromGitHub {
      owner = "minio";
      repo = "kes";
      rev = "2024-03-28T12-56-37Z";
      fetchSubmodules = false;
      sha256 = "sha256-iOdwMqhZEhYE6iEiDHKURpZ1hwqO6sjuYkqfD+DvkXI=";
    };
  };
  ocis-bin = {
    pname = "ocis-bin";
    version = "5.0.1";
    src = fetchurl {
      url = "https://github.com/owncloud/ocis/releases/download/v5.0.1/ocis-5.0.1-linux-amd64";
      sha256 = "sha256-Fz0ee0Lu0CL3xJbsp1CCl0rsN/p48BdOj8oVOf0QSh4=";
    };
  };
  plasma-panel-spacer-extended = {
    pname = "plasma-panel-spacer-extended";
    version = "v1.5.4";
    src = fetchFromGitHub {
      owner = "luisbocanegra";
      repo = "plasma-panel-spacer-extended";
      rev = "v1.5.4";
      fetchSubmodules = false;
      sha256 = "sha256-TZD+Tm6iBS6B3O2tu816PUSXbPH2W37ZZD9HDqHEGv8=";
    };
  };
  sierra-breeze-enhanced-kde6 = {
    pname = "sierra-breeze-enhanced-kde6";
    version = "3b224129e52fcf1998aa0312cb5f534a6d67b555";
    src = fetchgit {
      url = "https://github.com/chiyuki0325/SierraBreezeEnhanced6";
      rev = "3b224129e52fcf1998aa0312cb5f534a6d67b555";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-cDoBIou9JsgcR+cKzTLvXZ+xIoZKvIuO3S0XsTVPvKE=";
    };
    date = "2024-03-29";
  };
  wemeet = {
    pname = "wemeet";
    version = "3.14.0.401";
    src = fetchurl {
      url = "https://updatecdn.meeting.qq.com/cos/1b001ef75914a1d6948decb8c2550b47/TencentMeeting_0300000000_3.14.0.401_x86_64_default.publish.deb";
      sha256 = "sha256-ioBlxrdTboLSRXO9BhmdPFl5M0chaEoPgVLsami1Gy8=";
    };
  };
}
