# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  aosc-scriptlets = {
    pname = "aosc-scriptlets";
    version = "5a9230041ef5128729cead141e55ab7946553537";
    src = fetchgit {
      url = "https://github.com/AOSC-Dev/scriptlets";
      rev = "5a9230041ef5128729cead141e55ab7946553537";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Zy2piPDjBn51aGjA5DwlQvTiQodoiKjjO0s+62JJ8BA=";
    };
    date = "2025-05-10";
  };
  fcitx5-pinyin-moegirl = {
    pname = "fcitx5-pinyin-moegirl";
    version = "20250509";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20250509/moegirl.dict";
      sha256 = "sha256-M0oquFoR44IRY3dvTjpZ48tRTi+OP+GqMfb5sdUcurY=";
    };
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20250415";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.5/zhwiki-20250415.dict";
      sha256 = "sha256-8dFBoP3UcYCl6EYojn14Bp7aYe/Z9cf4drSmeheHbLw=";
    };
  };
  sierra-breeze-enhanced-git = {
    pname = "sierra-breeze-enhanced-git";
    version = "V.2.1.0";
    src = fetchFromGitHub {
      owner = "kupiqu";
      repo = "SierraBreezeEnhanced";
      rev = "V.2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-Dzsl06FdCRGuBv2K5BmowCdaWQpYhe/U7aeQ0Q1T5Z4=";
    };
  };
}
