# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  fcitx5-pinyin-moegirl = {
    pname = "fcitx5-pinyin-moegirl";
    version = "20250810";
    src = fetchurl {
      url = "https://github.com/outloudvi/mw2fcitx/releases/download/20250810/moegirl.dict";
      sha256 = "sha256-PuuW43+uu9Vasy33KW1IKb2uK2mh8M/V9fVCVp1QZl0=";
    };
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20250823";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.5/zhwiki-20250823.dict";
      sha256 = "sha256-cD0FKxPvdQfcrfR/Fh4aNb+pK/IFiFLyvg8LhnYI+vs=";
    };
  };
  moviepilot-core = {
    pname = "moviepilot-core";
    version = "v2.7.9";
    src = fetchFromGitHub {
      owner = "jxxghp";
      repo = "MoviePilot";
      rev = "v2.7.9";
      fetchSubmodules = false;
      sha256 = "sha256-8VXMKwexslGf7ekhYdgqpO1UoBa64jgGjKvoFj7wl+c=";
    };
  };
  moviepilot-frontend = {
    pname = "moviepilot-frontend";
    version = "v2.8.0";
    src = fetchFromGitHub {
      owner = "jxxghp";
      repo = "MoviePilot-Frontend";
      rev = "v2.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-fprEU7azGsGh+Zv5y6xguVcVOK/ipwEjs8u2kon5SdA=";
    };
  };
  moviepilot-plugins = {
    pname = "moviepilot-plugins";
    version = "fe8a7c6cd26cb1a8fbf262eab9c859947142fdf0";
    src = fetchFromGitHub {
      owner = "jxxghp";
      repo = "MoviePilot-Plugins";
      rev = "fe8a7c6cd26cb1a8fbf262eab9c859947142fdf0";
      fetchSubmodules = false;
      sha256 = "sha256-RxUQrYYs7LGkENO1AtFoFzym2JldP5oYD4PVzQ0jgCw=";
    };
    date = "2025-09-09";
  };
  moviepilot-resources = {
    pname = "moviepilot-resources";
    version = "5a9e4a0a71e0eacdca85cc31ce4e3b131f3501d6";
    src = fetchFromGitHub {
      owner = "jxxghp";
      repo = "MoviePilot-Resources";
      rev = "5a9e4a0a71e0eacdca85cc31ce4e3b131f3501d6";
      fetchSubmodules = false;
      sha256 = "sha256-lTHwf3tmETt/qMGi/NBHRw2YkDMK10jmzjcz4afNTV0=";
    };
    date = "2025-09-02";
  };
  sierra-breeze-enhanced-git = {
    pname = "sierra-breeze-enhanced-git";
    version = "V.2.1.0";
    src = fetchFromGitHub {
      owner = "kupiqu";
      repo = "SierraBreezeEnhanced";
      rev = "V.2.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-Dzsl06FdCRGuBv2K5BmowCdaWQpYhe/U7aeQ0Q1T5Z4=";
    };
  };
}
