[project]
name = "moviepilot"
version = "2.8.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles~=24.1.0",
    "aiopathlib~=0.6.0",
    "aioshutil~=1.5",
    "aiosqlite~=0.21.0",
    "alembic~=1.16.2",
    "anitopy~=2.1.1",
    "apscheduler~=3.11.0",
    "async-timeout~=5.0.1 ; python_full_version < '3.11.3'",
    "asyncpg~=0.30.0",
    "asynctempfile~=0.5.0",
    "bcrypt~=4.0.1",
    "beautifulsoup4~=4.13.4",
    "bs4~=0.0.2",
    "cacheout~=0.16.0",
    "cachetools~=6.1.0",
    "cf-clearance~=0.31.0",
    "chardet~=5.2.0",
    "click~=8.2.1",
    "cn2an~=0.5.19",
    "cryptography~=45.0.4",
    "cython~=3.1.2",
    "dateparser~=1.2.2",
    "docker~=7.1.0",
    "fast-bencode~=1.1.7",
    "fastapi~=0.115.14",
    "func-timeout==4.3.5",
    "httpx[socks]~=0.28.1",
    "jieba~=0.42.1",
    "jinja2~=3.1.6",
    "lxml~=6.0.0",
    "oss2~=2.19.1",
    "packaging~=25.0",
    "parse~=1.20.2",
    "passlib~=1.7.4",
    "pillow~=11.2.1",
    "pillow-avif-plugin~=1.5.2",
    "pinyin2hanzi~=0.1.1",
    "playwright~=1.53.0",
    "plexapi~=4.17.0",
    "psutil~=7.0.0",
    "psycopg2-binary~=2.9.10",
    "pycryptodome~=3.23.0",
    "pydantic~=1.10.22",
    "pyjwt~=2.10.1",
    "pympler~=1.1",
    "pyotp~=2.9.0",
    "pyparsing~=3.2.3",
    "pyquery~=2.0.1",
    "pystray~=0.19.5",
    "pytelegrambotapi~=4.27.0",
    "python-dateutil~=2.8.2",
    "python-dotenv~=1.1.1",
    "python-hosts~=1.1.2",
    "python-multipart~=0.0.9",
    "pytz~=2025.2",
    "pyvirtualdisplay~=3.0",
    "pywebpush~=2.0.3",
    "pywin32==310 ; sys_platform == 'win32'",
    "qbittorrent-api==2025.5.0",
    "redis~=6.2.0",
    "regex~=2024.11.6",
    "requests-cache~=1.2.1",
    "requests[socks]~=2.32.4",
    "rsa~=4.9",
    "ruamel-yaml~=0.18.14",
    "setproctitle~=1.3.6",
    "setuptools~=78.1.0",
    "slack-bolt~=1.23.0",
    "slack-sdk~=3.35.0",
    "smbprotocol~=1.15.0",
    "sqlalchemy~=2.0.41",
    "starlette~=0.46.2",
    "torrentool~=1.2.0",
    "tqdm~=4.67.1",
    "transmission-rpc~=4.3.0",
    "urllib3~=2.5.0",
    "uvicorn~=0.34.3",
    "watchdog~=6.0.0",
    "watchfiles~=1.1.0",
    "zhconv~=1.4.3",
]
