name: "Build packages"

on:
  workflow_call:
    inputs:
      packages:
        description: JSON array of packages to build
        required: true
        type: string
      push_cache:
        description: Push cache to Cachix
        default: false
        type: boolean
      pre_check:
        description: Check evaluation
        default: false
        type: boolean

env:
  nix_conf: |
    keep-env-derivations = true
    keep-outputs = true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      CI_MODE: 1
      CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(inputs.packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v33
        with:
          nix_conf: ${{ env.nix_conf }}

      - name: Setup cache
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nur-${{ runner.os }}-individual-${{ matrix.package }}-${{ hashFiles('flake.lock', 'pkgs/_sources/generated.nix') }}
          restore-prefixes-first-match: nur-${{ runner.os }}-shared-${{ hashFiles('flake.lock', 'pkgs/_sources/generated.nix') }}
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nur-${{ runner.os }}-individual-${{ matrix.package }}-
          purge-created: 0
          purge-primary-key: never

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: '${{ secrets.CACHIX_CACHE }}'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ inputs.push_cache != true }}

      - name: Show flake metadata
        if: ${{ inputs.pre_check == true }}
        run: nix flake metadata

      - name: Show flake information
        if: ${{ inputs.pre_check == true }}
        run: nix flake show

      - name: Check evaluation
        if: ${{ inputs.pre_check == true }}
        run: nix flake check --no-build --no-allow-import-from-derivation

      - name: Build ${{ matrix.package }}
        run: |
          nix build .#packages.x86_64-linux.${{ matrix.package }} -v --show-trace

      - name: Push cache to Cachix
        if: ${{ inputs.push_cache == true }}
        run: bash ./.github/push_cache.sh ${{ matrix.package }}
