name: "Manaully build and populate cache"

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to build'
        required: true
      is_push:
        description: 'Push cache'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NIXPKGS_ALLOW_UNFREE: 1
      ATTIC_SERVER: ${{ secrets.ATTIC_SERVER }}
      ATTIC_CACHE: ${{ secrets.ATTIC_CACHE }}
      ATTIC_ACCESS_TOKEN: ${{ secrets.ATTIC_ACCESS_TOKEN }}

    steps:
    - name: Maximize space
      # https://github.com/Ninlives/emerge/blob/master/.github/workflows/os.yml#L15
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        echo "Available space:"
        df -h

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Attic
      run: |
        curl -L https://raw.githubusercontent.com/zhaofengli/attic/main/.github/install-attic-ci.sh -O
        bash install-attic-ci.sh
        # https://github.com/zhaofengli/attic/blob/main/.github/workflows/build.yml#L30
        export PATH=$HOME/.nix-profile/bin:$PATH
        attic login --set-default ci "$ATTIC_SERVER" "$ATTIC_ACCESS_TOKEN"

    - name: Update package sources
      run: |
        nix flake update --impure
        nix run .#update --impure

    - name: Show flake metadata
      run: nix flake metadata --impure

    - name: Show flake information
      run: nix flake show --impure

    - name: Check evaluation
      run: nix flake check --no-build --no-allow-import-from-derivation --impure

    - name: Build nix package
      env:
        PKGNAME: ${{ inputs.package }}
      run: nix-build .#$PKGNAME --impure -v

    - name: Upload Attic
      if: ${{ inputs.is_push == true }}
      run: |
        bash ./.github/push_cache.sh $PKGNAME
