name: "Update flake.lock"

on:
  schedule:
    - cron:  '19 18 1,13 * *'
  repository_dispatch:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NIXPKGS_ALLOW_UNFREE: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update package sources
      run: |
        nix flake update --impure

    - name: Show flake metadata
      run: nix flake metadata --impure

    - name: Push flake.lock
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update: flake.lock"
        file_pattern: "flake.lock"
